export enum CategorieEnum {
  TECHNOLOGY = 'Technology',
  TRAVEL = 'Travel',
  FOOD = 'Food',
  FITNESS = 'Fitness',
  LIFESTYLE = 'Lifestyle',
  FASHION = 'Fashion',
  HEALTH = 'Health',
  BOOKS = 'Books',
  SPORTS = 'Sports',
  ENTERTAINMENT = 'Entertainment',
  DIY = 'DIY',
  MUSIC = 'Music',
  PERSONAL_DEVELOPMENT = 'Personal Development',
  BUSINESS = 'Business',
  EDUCATION = 'Education',
  SCIENCE = 'Science',
  ART = 'Art',
  PARENTING = 'Parenting',
  HOBBIES = 'Hobbies',
  PHOTOGRAPHY = 'Photography',
  GAMING = 'Gaming',
  DESIGN = 'Design',
  SOCIAL_MEDIA = 'Social Media',
  POLITICAL = 'Political',
  NONE = 'None',
}
